### ISSUE TITLE
Images are not compressing while DICOM Forward

### ISSUE THREAD

**Issue by arunjoshtech** [marcelvanherk/Conquest-DICOM-Server#36] opened 2023-08-31 15:11 UTC
The transfer syntax for attached images not functioning while forward Images to PACS.  The images going uncompressed for both Lossy and lossless compression.
[0200030003_anon.zip](https://github.com/marcelvanherk/Conquest-DICOM-Server/files/12487506/0200030003_anon.zip)

**Comment by marcelvanherk** [comment] 2023-08-31 16:33
I need more information. What is your configuration and what rules are you using? Does it work for other images? It may be that the PACS does not accept the compresssion requested. Image seems normal.

**Comment by arunjoshtech** [comment] 2023-08-31 18:15
we are using 1.50b version almost same more than 20 locations.  For this site for both CT and MRI images are not getting compressed in windows 7. And same images getting compressed in another gdcm based dicom gateway while send it.
I have tested the samples images in my computer running windows 10 produced same issues with latest 1.5.0d.
Kindly check it using given attached DICOM images at your end.

**Comment by marcelvanherk** [comment] 2023-08-31 19:12
What is the configuration? Forward statement and receiving archive.

**Comment by arunjoshtech** [comment] 2023-08-31 19:55
Foorward statement
exportconverters=1
exportconverter0 = forward series to KCPDICOM after 10.

Known dicom transfer syntax selected is j7.
Receiving archive statement  at our DICOM services (KCPDICOM SCP services)?

**Comment by marcelvanherk** [comment] 2023-08-31 20:29
Seem to compress for me?

[CONQUESTSRV1] Accepted compression: js
[CONQUESTSRV1] MyStudyRootRetrieveGeneric :: RetrieveOn
[CONQUESTSRV1] Locating file:MAG0 00000000\1.2.840.113704.9.1000.16.1.2023083118592965400020002_0003_000003_16935133850000.dcm
[CONQUESTSRV1] ReadAheadThread: readahead > 0000
[CONQUESTSRV1] RetrieveOn: givenout < 0000
[CONQUESTSRV1] Sending file : c:\dicom150d_minimal\data\00000000\1.2.840.113704.9.1000.16.1.2023083118592965400020002_0003_000003_16935133850000.dcm
[CONQUESTSRV1] Image Loaded from Read Ahead Thread, returning TRUE
[CONQUESTSRV1] JPEG-LS compress started.
[CONQUESTSRV1] Debug[CompressJPEGLS]: H = 512, W = 512, Bits = 12 in 16, Components = 1, Frames = 1
[CONQUESTSRV1] JPEG-LS compress 524288 bytes to 180150 bytes
[CONQUESTSRV1] JPEGLS compress time 15 milliseconds.

Can you catch the relevant bit of the log file?

**Comment by marcelvanherk** [comment] 2024-09-28 14:31
Closed as unable to reproduce

**Closed as completed by marcelvanherk** 2024-09-28 14:31 UTC

**Comment by arunjoshtech** [comment] 2024-09-29 14:37
Hi, was unable to respond due to unavoidable situation, Now I have downloaded  latest conquest server, with above same procedure uploaded images is being uncompressed? from where I can take log for this to submit to you? I have three pc with this problem, b and e versions running. tried with all transfer syntax too

**Comment by marcelvanherk** [comment] 2024-09-29 16:37
Hi

mail it to ***@***.***

Marcel
